###################  项目启动端口  ###################
server:
  port: 2222

infinitus:
  swagger-open: true #是否开启swagger (true/false)


###################  spring配置  ###################
spring:
  profiles: dev-tdg
  datasource:
      url: jdbc:mysql://119.23.143.93:3306/infinitus?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: fishgogogo
      db-name: infinitus
      filters: log4j,wall,mergeStat


###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:cloud/module/repository/**/mapping/*.xml
  typeAliasesPackage: cloud.module.repository.model
  typeEnumsPackage: cloud.module.repository.constant.enums
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用