spring:
  profiles: dev-cbc
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      enabled: true #默认支持文件上传
      file-size-threshold: 0 #支持文件写入磁盘
      #location: /data/infinitus_file/temporary #上传文件的临时目录
      location: d:/test #上传文件的临时目录
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
    #   maxFileSize: 100Mb #最大文件大小
    #   maxRequestSize: 100MB #最大请求大小
    encoding:
      force: true
      charset: UTF-8
      enabled: true
      uri-encoding: UTF-8

infinitus:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  #file-upload-path: /data/infinitus_file/actual  #文件上传目录(不配置的话为java.io.tmpdir目录)
  file-upload-path: d:/test  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: true #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  common-pwd: $Abc123
  file-domain: 
