###################  项目启动端口  ###################
server:
  port: 333


##########################################################
##################  所有profile共有的配置  #################
##########################################################


###################  infinitus配置  ###################
infinitus:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  file-upload-path: e:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: true #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  common-pwd: $Abc123

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false


###################  spring配置  ###################
spring:
  datasource:
      url: jdbc:mysql://119.23.143.93:3306/infinitus?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: fishgogogo
      db-name: infinitus
      filters: log4j,wall,mergeStat
  redis:
    host: 119.23.143.93
    # host: localhost
    port: 6379
    password:
    timeout: 5000
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      enabled: true #默认支持文件上传
      file-size-threshold: 0 #支持文件写入磁盘
      location: e:/test #上传文件的临时目录
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
      livereload.enabled: false
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:cloud/module/repository/**/mapping/*.xml
  typeAliasesPackage: cloud.module.repository.model
  typeEnumsPackage: cloud.module.repository.constant.enums
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---

##########################################################
###################  开发环境的profile  ###################
##########################################################



#多数据源配置
infinitus:
  muti-datasource:
    default-dataSource-name: dataSourceSystem #默认的数据源名称
    url: jdbc:mysql://119.23.143.93:3306/infinitus_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: fishgogogo

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: infinitus.log



#  logging.level.tk.mybatis=TRACE
#  logging.level.com.framework=TRACE
#
#  pagehelper.helperDialect=mysql
#  pagehelper.reasonable=true
#  pagehelper.supportMethodsArguments=true
#  pagehelper.params=count=countSql
#
#  mybatis.type-aliases-package=cloud.module.repository.model
#  mybatis.mapper-locations=classpath*:/mappers/**.xml
#  mapper.mappers=cloud.module.repository.util.MyMapper
#  mapper.not-empty=true
#  mapper.identity=MYSQL
#  mybatis.configuration.mapUnderscoreToCamelCase=true
#